// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.31.0
// 	protoc        v3.21.12
// source: internal/deliver/grpc/proto/image.proto

package stub

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type ImageRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Name    *string `protobuf:"bytes,1,opt,name=name,proto3,oneof" json:"name,omitempty"`
	RepoTag *string `protobuf:"bytes,2,opt,name=repoTag,proto3,oneof" json:"repoTag,omitempty"`
}

func (x *ImageRequest) Reset() {
	*x = ImageRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_internal_deliver_grpc_proto_image_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ImageRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ImageRequest) ProtoMessage() {}

func (x *ImageRequest) ProtoReflect() protoreflect.Message {
	mi := &file_internal_deliver_grpc_proto_image_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ImageRequest.ProtoReflect.Descriptor instead.
func (*ImageRequest) Descriptor() ([]byte, []int) {
	return file_internal_deliver_grpc_proto_image_proto_rawDescGZIP(), []int{0}
}

func (x *ImageRequest) GetName() string {
	if x != nil && x.Name != nil {
		return *x.Name
	}
	return ""
}

func (x *ImageRequest) GetRepoTag() string {
	if x != nil && x.RepoTag != nil {
		return *x.RepoTag
	}
	return ""
}

type ImageHeaderReply struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Id      int32  `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	Name    string `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	RepoTag string `protobuf:"bytes,3,opt,name=repoTag,proto3" json:"repoTag,omitempty"`
}

func (x *ImageHeaderReply) Reset() {
	*x = ImageHeaderReply{}
	if protoimpl.UnsafeEnabled {
		mi := &file_internal_deliver_grpc_proto_image_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ImageHeaderReply) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ImageHeaderReply) ProtoMessage() {}

func (x *ImageHeaderReply) ProtoReflect() protoreflect.Message {
	mi := &file_internal_deliver_grpc_proto_image_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ImageHeaderReply.ProtoReflect.Descriptor instead.
func (*ImageHeaderReply) Descriptor() ([]byte, []int) {
	return file_internal_deliver_grpc_proto_image_proto_rawDescGZIP(), []int{1}
}

func (x *ImageHeaderReply) GetId() int32 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *ImageHeaderReply) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *ImageHeaderReply) GetRepoTag() string {
	if x != nil {
		return x.RepoTag
	}
	return ""
}

type ImageHeaderListResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Images []*ImageHeaderReply `protobuf:"bytes,1,rep,name=images,proto3" json:"images,omitempty"`
}

func (x *ImageHeaderListResponse) Reset() {
	*x = ImageHeaderListResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_internal_deliver_grpc_proto_image_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ImageHeaderListResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ImageHeaderListResponse) ProtoMessage() {}

func (x *ImageHeaderListResponse) ProtoReflect() protoreflect.Message {
	mi := &file_internal_deliver_grpc_proto_image_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ImageHeaderListResponse.ProtoReflect.Descriptor instead.
func (*ImageHeaderListResponse) Descriptor() ([]byte, []int) {
	return file_internal_deliver_grpc_proto_image_proto_rawDescGZIP(), []int{2}
}

func (x *ImageHeaderListResponse) GetImages() []*ImageHeaderReply {
	if x != nil {
		return x.Images
	}
	return nil
}

type ImageDetailedReply struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Id      int32  `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	Name    string `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	RepoTag string `protobuf:"bytes,3,opt,name=repoTag,proto3" json:"repoTag,omitempty"`
}

func (x *ImageDetailedReply) Reset() {
	*x = ImageDetailedReply{}
	if protoimpl.UnsafeEnabled {
		mi := &file_internal_deliver_grpc_proto_image_proto_msgTypes[3]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ImageDetailedReply) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ImageDetailedReply) ProtoMessage() {}

func (x *ImageDetailedReply) ProtoReflect() protoreflect.Message {
	mi := &file_internal_deliver_grpc_proto_image_proto_msgTypes[3]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ImageDetailedReply.ProtoReflect.Descriptor instead.
func (*ImageDetailedReply) Descriptor() ([]byte, []int) {
	return file_internal_deliver_grpc_proto_image_proto_rawDescGZIP(), []int{3}
}

func (x *ImageDetailedReply) GetId() int32 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *ImageDetailedReply) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *ImageDetailedReply) GetRepoTag() string {
	if x != nil {
		return x.RepoTag
	}
	return ""
}

type ImageId struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Value int32 `protobuf:"varint,1,opt,name=value,proto3" json:"value,omitempty"`
}

func (x *ImageId) Reset() {
	*x = ImageId{}
	if protoimpl.UnsafeEnabled {
		mi := &file_internal_deliver_grpc_proto_image_proto_msgTypes[4]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ImageId) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ImageId) ProtoMessage() {}

func (x *ImageId) ProtoReflect() protoreflect.Message {
	mi := &file_internal_deliver_grpc_proto_image_proto_msgTypes[4]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ImageId.ProtoReflect.Descriptor instead.
func (*ImageId) Descriptor() ([]byte, []int) {
	return file_internal_deliver_grpc_proto_image_proto_rawDescGZIP(), []int{4}
}

func (x *ImageId) GetValue() int32 {
	if x != nil {
		return x.Value
	}
	return 0
}

type ImageSpecification struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Name string `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
}

func (x *ImageSpecification) Reset() {
	*x = ImageSpecification{}
	if protoimpl.UnsafeEnabled {
		mi := &file_internal_deliver_grpc_proto_image_proto_msgTypes[5]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ImageSpecification) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ImageSpecification) ProtoMessage() {}

func (x *ImageSpecification) ProtoReflect() protoreflect.Message {
	mi := &file_internal_deliver_grpc_proto_image_proto_msgTypes[5]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ImageSpecification.ProtoReflect.Descriptor instead.
func (*ImageSpecification) Descriptor() ([]byte, []int) {
	return file_internal_deliver_grpc_proto_image_proto_rawDescGZIP(), []int{5}
}

func (x *ImageSpecification) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

type ImageKey struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Key string `protobuf:"bytes,1,opt,name=key,proto3" json:"key,omitempty"`
}

func (x *ImageKey) Reset() {
	*x = ImageKey{}
	if protoimpl.UnsafeEnabled {
		mi := &file_internal_deliver_grpc_proto_image_proto_msgTypes[6]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ImageKey) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ImageKey) ProtoMessage() {}

func (x *ImageKey) ProtoReflect() protoreflect.Message {
	mi := &file_internal_deliver_grpc_proto_image_proto_msgTypes[6]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ImageKey.ProtoReflect.Descriptor instead.
func (*ImageKey) Descriptor() ([]byte, []int) {
	return file_internal_deliver_grpc_proto_image_proto_rawDescGZIP(), []int{6}
}

func (x *ImageKey) GetKey() string {
	if x != nil {
		return x.Key
	}
	return ""
}

type ImageEmptyReply struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *ImageEmptyReply) Reset() {
	*x = ImageEmptyReply{}
	if protoimpl.UnsafeEnabled {
		mi := &file_internal_deliver_grpc_proto_image_proto_msgTypes[7]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ImageEmptyReply) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ImageEmptyReply) ProtoMessage() {}

func (x *ImageEmptyReply) ProtoReflect() protoreflect.Message {
	mi := &file_internal_deliver_grpc_proto_image_proto_msgTypes[7]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ImageEmptyReply.ProtoReflect.Descriptor instead.
func (*ImageEmptyReply) Descriptor() ([]byte, []int) {
	return file_internal_deliver_grpc_proto_image_proto_rawDescGZIP(), []int{7}
}

type ImagePruneReply struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Content string `protobuf:"bytes,1,opt,name=content,proto3" json:"content,omitempty"`
}

func (x *ImagePruneReply) Reset() {
	*x = ImagePruneReply{}
	if protoimpl.UnsafeEnabled {
		mi := &file_internal_deliver_grpc_proto_image_proto_msgTypes[8]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ImagePruneReply) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ImagePruneReply) ProtoMessage() {}

func (x *ImagePruneReply) ProtoReflect() protoreflect.Message {
	mi := &file_internal_deliver_grpc_proto_image_proto_msgTypes[8]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ImagePruneReply.ProtoReflect.Descriptor instead.
func (*ImagePruneReply) Descriptor() ([]byte, []int) {
	return file_internal_deliver_grpc_proto_image_proto_rawDescGZIP(), []int{8}
}

func (x *ImagePruneReply) GetContent() string {
	if x != nil {
		return x.Content
	}
	return ""
}

var File_internal_deliver_grpc_proto_image_proto protoreflect.FileDescriptor

var file_internal_deliver_grpc_proto_image_proto_rawDesc = []byte{
	0x0a, 0x27, 0x69, 0x6e, 0x74, 0x65, 0x72, 0x6e, 0x61, 0x6c, 0x2f, 0x64, 0x65, 0x6c, 0x69, 0x76,
	0x65, 0x72, 0x2f, 0x67, 0x72, 0x70, 0x63, 0x2f, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2f, 0x69, 0x6d,
	0x61, 0x67, 0x65, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x22, 0x5b, 0x0a, 0x0c, 0x49, 0x6d, 0x61,
	0x67, 0x65, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x17, 0x0a, 0x04, 0x6e, 0x61, 0x6d,
	0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x48, 0x00, 0x52, 0x04, 0x6e, 0x61, 0x6d, 0x65, 0x88,
	0x01, 0x01, 0x12, 0x1d, 0x0a, 0x07, 0x72, 0x65, 0x70, 0x6f, 0x54, 0x61, 0x67, 0x18, 0x02, 0x20,
	0x01, 0x28, 0x09, 0x48, 0x01, 0x52, 0x07, 0x72, 0x65, 0x70, 0x6f, 0x54, 0x61, 0x67, 0x88, 0x01,
	0x01, 0x42, 0x07, 0x0a, 0x05, 0x5f, 0x6e, 0x61, 0x6d, 0x65, 0x42, 0x0a, 0x0a, 0x08, 0x5f, 0x72,
	0x65, 0x70, 0x6f, 0x54, 0x61, 0x67, 0x22, 0x50, 0x0a, 0x10, 0x49, 0x6d, 0x61, 0x67, 0x65, 0x48,
	0x65, 0x61, 0x64, 0x65, 0x72, 0x52, 0x65, 0x70, 0x6c, 0x79, 0x12, 0x0e, 0x0a, 0x02, 0x69, 0x64,
	0x18, 0x01, 0x20, 0x01, 0x28, 0x05, 0x52, 0x02, 0x69, 0x64, 0x12, 0x12, 0x0a, 0x04, 0x6e, 0x61,
	0x6d, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x6e, 0x61, 0x6d, 0x65, 0x12, 0x18,
	0x0a, 0x07, 0x72, 0x65, 0x70, 0x6f, 0x54, 0x61, 0x67, 0x18, 0x03, 0x20, 0x01, 0x28, 0x09, 0x52,
	0x07, 0x72, 0x65, 0x70, 0x6f, 0x54, 0x61, 0x67, 0x22, 0x44, 0x0a, 0x17, 0x49, 0x6d, 0x61, 0x67,
	0x65, 0x48, 0x65, 0x61, 0x64, 0x65, 0x72, 0x4c, 0x69, 0x73, 0x74, 0x52, 0x65, 0x73, 0x70, 0x6f,
	0x6e, 0x73, 0x65, 0x12, 0x29, 0x0a, 0x06, 0x69, 0x6d, 0x61, 0x67, 0x65, 0x73, 0x18, 0x01, 0x20,
	0x03, 0x28, 0x0b, 0x32, 0x11, 0x2e, 0x49, 0x6d, 0x61, 0x67, 0x65, 0x48, 0x65, 0x61, 0x64, 0x65,
	0x72, 0x52, 0x65, 0x70, 0x6c, 0x79, 0x52, 0x06, 0x69, 0x6d, 0x61, 0x67, 0x65, 0x73, 0x22, 0x52,
	0x0a, 0x12, 0x49, 0x6d, 0x61, 0x67, 0x65, 0x44, 0x65, 0x74, 0x61, 0x69, 0x6c, 0x65, 0x64, 0x52,
	0x65, 0x70, 0x6c, 0x79, 0x12, 0x0e, 0x0a, 0x02, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x05,
	0x52, 0x02, 0x69, 0x64, 0x12, 0x12, 0x0a, 0x04, 0x6e, 0x61, 0x6d, 0x65, 0x18, 0x02, 0x20, 0x01,
	0x28, 0x09, 0x52, 0x04, 0x6e, 0x61, 0x6d, 0x65, 0x12, 0x18, 0x0a, 0x07, 0x72, 0x65, 0x70, 0x6f,
	0x54, 0x61, 0x67, 0x18, 0x03, 0x20, 0x01, 0x28, 0x09, 0x52, 0x07, 0x72, 0x65, 0x70, 0x6f, 0x54,
	0x61, 0x67, 0x22, 0x1f, 0x0a, 0x07, 0x49, 0x6d, 0x61, 0x67, 0x65, 0x49, 0x64, 0x12, 0x14, 0x0a,
	0x05, 0x76, 0x61, 0x6c, 0x75, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x05, 0x52, 0x05, 0x76, 0x61,
	0x6c, 0x75, 0x65, 0x22, 0x28, 0x0a, 0x12, 0x49, 0x6d, 0x61, 0x67, 0x65, 0x53, 0x70, 0x65, 0x63,
	0x69, 0x66, 0x69, 0x63, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x12, 0x12, 0x0a, 0x04, 0x6e, 0x61, 0x6d,
	0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x6e, 0x61, 0x6d, 0x65, 0x22, 0x1c, 0x0a,
	0x08, 0x49, 0x6d, 0x61, 0x67, 0x65, 0x4b, 0x65, 0x79, 0x12, 0x10, 0x0a, 0x03, 0x6b, 0x65, 0x79,
	0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x03, 0x6b, 0x65, 0x79, 0x22, 0x11, 0x0a, 0x0f, 0x49,
	0x6d, 0x61, 0x67, 0x65, 0x45, 0x6d, 0x70, 0x74, 0x79, 0x52, 0x65, 0x70, 0x6c, 0x79, 0x22, 0x2b,
	0x0a, 0x0f, 0x49, 0x6d, 0x61, 0x67, 0x65, 0x50, 0x72, 0x75, 0x6e, 0x65, 0x52, 0x65, 0x70, 0x6c,
	0x79, 0x12, 0x18, 0x0a, 0x07, 0x63, 0x6f, 0x6e, 0x74, 0x65, 0x6e, 0x74, 0x18, 0x01, 0x20, 0x01,
	0x28, 0x09, 0x52, 0x07, 0x63, 0x6f, 0x6e, 0x74, 0x65, 0x6e, 0x74, 0x32, 0xfa, 0x01, 0x0a, 0x0c,
	0x49, 0x6d, 0x61, 0x67, 0x65, 0x53, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x12, 0x23, 0x0a, 0x06,
	0x43, 0x72, 0x65, 0x61, 0x74, 0x65, 0x12, 0x0d, 0x2e, 0x49, 0x6d, 0x61, 0x67, 0x65, 0x52, 0x65,
	0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x08, 0x2e, 0x49, 0x6d, 0x61, 0x67, 0x65, 0x49, 0x64, 0x22,
	0x00, 0x12, 0x3a, 0x0a, 0x07, 0x46, 0x69, 0x6e, 0x64, 0x41, 0x6c, 0x6c, 0x12, 0x13, 0x2e, 0x49,
	0x6d, 0x61, 0x67, 0x65, 0x53, 0x70, 0x65, 0x63, 0x69, 0x66, 0x69, 0x63, 0x61, 0x74, 0x69, 0x6f,
	0x6e, 0x1a, 0x18, 0x2e, 0x49, 0x6d, 0x61, 0x67, 0x65, 0x48, 0x65, 0x61, 0x64, 0x65, 0x72, 0x4c,
	0x69, 0x73, 0x74, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x22, 0x00, 0x12, 0x2a, 0x0a,
	0x06, 0x47, 0x65, 0x74, 0x4f, 0x6e, 0x65, 0x12, 0x09, 0x2e, 0x49, 0x6d, 0x61, 0x67, 0x65, 0x4b,
	0x65, 0x79, 0x1a, 0x13, 0x2e, 0x49, 0x6d, 0x61, 0x67, 0x65, 0x44, 0x65, 0x74, 0x61, 0x69, 0x6c,
	0x65, 0x64, 0x52, 0x65, 0x70, 0x6c, 0x79, 0x22, 0x00, 0x12, 0x2a, 0x0a, 0x09, 0x44, 0x65, 0x6c,
	0x65, 0x74, 0x65, 0x4f, 0x6e, 0x65, 0x12, 0x09, 0x2e, 0x49, 0x6d, 0x61, 0x67, 0x65, 0x4b, 0x65,
	0x79, 0x1a, 0x10, 0x2e, 0x49, 0x6d, 0x61, 0x67, 0x65, 0x45, 0x6d, 0x70, 0x74, 0x79, 0x52, 0x65,
	0x70, 0x6c, 0x79, 0x22, 0x00, 0x12, 0x31, 0x0a, 0x06, 0x44, 0x65, 0x6c, 0x65, 0x74, 0x65, 0x12,
	0x13, 0x2e, 0x49, 0x6d, 0x61, 0x67, 0x65, 0x53, 0x70, 0x65, 0x63, 0x69, 0x66, 0x69, 0x63, 0x61,
	0x74, 0x69, 0x6f, 0x6e, 0x1a, 0x10, 0x2e, 0x49, 0x6d, 0x61, 0x67, 0x65, 0x50, 0x72, 0x75, 0x6e,
	0x65, 0x52, 0x65, 0x70, 0x6c, 0x79, 0x22, 0x00, 0x42, 0x1d, 0x5a, 0x1b, 0x2f, 0x69, 0x6e, 0x74,
	0x65, 0x72, 0x6e, 0x61, 0x6c, 0x2f, 0x64, 0x65, 0x6c, 0x69, 0x76, 0x65, 0x72, 0x2f, 0x67, 0x72,
	0x70, 0x63, 0x2f, 0x73, 0x74, 0x75, 0x62, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_internal_deliver_grpc_proto_image_proto_rawDescOnce sync.Once
	file_internal_deliver_grpc_proto_image_proto_rawDescData = file_internal_deliver_grpc_proto_image_proto_rawDesc
)

func file_internal_deliver_grpc_proto_image_proto_rawDescGZIP() []byte {
	file_internal_deliver_grpc_proto_image_proto_rawDescOnce.Do(func() {
		file_internal_deliver_grpc_proto_image_proto_rawDescData = protoimpl.X.CompressGZIP(file_internal_deliver_grpc_proto_image_proto_rawDescData)
	})
	return file_internal_deliver_grpc_proto_image_proto_rawDescData
}

var file_internal_deliver_grpc_proto_image_proto_msgTypes = make([]protoimpl.MessageInfo, 9)
var file_internal_deliver_grpc_proto_image_proto_goTypes = []interface{}{
	(*ImageRequest)(nil),            // 0: ImageRequest
	(*ImageHeaderReply)(nil),        // 1: ImageHeaderReply
	(*ImageHeaderListResponse)(nil), // 2: ImageHeaderListResponse
	(*ImageDetailedReply)(nil),      // 3: ImageDetailedReply
	(*ImageId)(nil),                 // 4: ImageId
	(*ImageSpecification)(nil),      // 5: ImageSpecification
	(*ImageKey)(nil),                // 6: ImageKey
	(*ImageEmptyReply)(nil),         // 7: ImageEmptyReply
	(*ImagePruneReply)(nil),         // 8: ImagePruneReply
}
var file_internal_deliver_grpc_proto_image_proto_depIdxs = []int32{
	1, // 0: ImageHeaderListResponse.images:type_name -> ImageHeaderReply
	0, // 1: ImageService.Create:input_type -> ImageRequest
	5, // 2: ImageService.FindAll:input_type -> ImageSpecification
	6, // 3: ImageService.GetOne:input_type -> ImageKey
	6, // 4: ImageService.DeleteOne:input_type -> ImageKey
	5, // 5: ImageService.Delete:input_type -> ImageSpecification
	4, // 6: ImageService.Create:output_type -> ImageId
	2, // 7: ImageService.FindAll:output_type -> ImageHeaderListResponse
	3, // 8: ImageService.GetOne:output_type -> ImageDetailedReply
	7, // 9: ImageService.DeleteOne:output_type -> ImageEmptyReply
	8, // 10: ImageService.Delete:output_type -> ImagePruneReply
	6, // [6:11] is the sub-list for method output_type
	1, // [1:6] is the sub-list for method input_type
	1, // [1:1] is the sub-list for extension type_name
	1, // [1:1] is the sub-list for extension extendee
	0, // [0:1] is the sub-list for field type_name
}

func init() { file_internal_deliver_grpc_proto_image_proto_init() }
func file_internal_deliver_grpc_proto_image_proto_init() {
	if File_internal_deliver_grpc_proto_image_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_internal_deliver_grpc_proto_image_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ImageRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_internal_deliver_grpc_proto_image_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ImageHeaderReply); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_internal_deliver_grpc_proto_image_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ImageHeaderListResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_internal_deliver_grpc_proto_image_proto_msgTypes[3].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ImageDetailedReply); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_internal_deliver_grpc_proto_image_proto_msgTypes[4].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ImageId); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_internal_deliver_grpc_proto_image_proto_msgTypes[5].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ImageSpecification); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_internal_deliver_grpc_proto_image_proto_msgTypes[6].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ImageKey); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_internal_deliver_grpc_proto_image_proto_msgTypes[7].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ImageEmptyReply); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_internal_deliver_grpc_proto_image_proto_msgTypes[8].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ImagePruneReply); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	file_internal_deliver_grpc_proto_image_proto_msgTypes[0].OneofWrappers = []interface{}{}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_internal_deliver_grpc_proto_image_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   9,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_internal_deliver_grpc_proto_image_proto_goTypes,
		DependencyIndexes: file_internal_deliver_grpc_proto_image_proto_depIdxs,
		MessageInfos:      file_internal_deliver_grpc_proto_image_proto_msgTypes,
	}.Build()
	File_internal_deliver_grpc_proto_image_proto = out.File
	file_internal_deliver_grpc_proto_image_proto_rawDesc = nil
	file_internal_deliver_grpc_proto_image_proto_goTypes = nil
	file_internal_deliver_grpc_proto_image_proto_depIdxs = nil
}
